# Vector Search with IRIS SQL
This tutorial covers how to use IRIS as a vector database. 

For this tutorial, we will use a dataset of 2.2k online reviews of scotch (
dataset from https://www.kaggle.com/datasets/koki25ando/22000-scotch-whisky-reviews) . With our latest vector database functionality, we can leverage the latest embedding models to run semantic search on the online reviews of scotch whiskeys. In addition, we'll be able to apply filters on columns with structured data. For example, we will be able to search for whiskeys that are priced under $100, and are 'earthy, smooth, and easy to drink'. Let's find our perfect whiskey!

First step is to do some imports and establish a connection to InterSystems IRIS.

In [11]:
import os, pandas as pd
from sentence_transformers import SentenceTransformer
from sqlalchemy import create_engine, text

username = 'demo'
password = 'demo'
hostname = os.getenv('IRIS_HOSTNAME', 'localhost')
port = '1972' 
namespace = 'USER'


# username = 'demo'
# password = 'demo'
# hostname = os.getenv('IRIS_HOSTNAME', 'localhost')
# port = '63958' 
# namespace = 'USER'

CONNECTION_STRING = f"iris://{username}:{password}@{hostname}:{port}/{namespace}"
#iris://demo:demo@localhost:63958/demo
engine = create_engine(CONNECTION_STRING)

## Exploring the dataset

Let's take a look at the data in our CSV file with whiskey reviews.

In [12]:
# Load the CSV file
df = pd.read_csv('../data/scotch_review.csv')
df.head()

,Unnamed: 0,name,category,review.point,price,currency,description
0,1,"Johnnie Walker Blue Label, 40%",Blended Scotch Whisky,97,225,$,"Magnificently powerful and intense. Caramels, dried peats, elegant cigar smoke, seeds scraped from vanilla beans, brand new pencils, peppercorn, coriander seeds, and star anise make for a deeply satisfying nosing experience. Silky caramels, bountiful fruits of ripe peach, stewed apple, orange pith, and pervasive smoke with elements of burnt tobacco. An abiding finish of smoke, dry spices, and banoffee pie sweetness. Close to perfection. Editor's Choice"
1,2,"Black Bowmore, 1964 vintage, 42 year old, 40.5%",Single Malt Scotch,97,4500.00,$,"What impresses me most is how this whisky evolves; it's incredibly complex. On the nose and palate, this is a thick, viscous, whisky with notes of sticky toffee, earthy oak, fig cake, roasted nuts, fallen fruit, pancake batter, black cherry, ripe peach, dark chocolate-covered espresso bean, polished leather, tobacco, a hint of wild game, and lingering, leafy damp kiln smoke. Flavors continue on the palate long after swallowing. This is what we all hope for (and dream of) in an older whisky!"
2,3,"Bowmore 46 year old (distilled 1964), 42.9%",Single Malt Scotch,97,13500.00,$,"There have been some legendary Bowmores from the mid-60s and this is every bit their equal. All of them share a remarkable aroma of tropical fruit, which here moves into hallucinatory intensity: guava, mango, peach, pineapple, grapefruit. There’s a very light touch of peat smoke, more a memory of Islay than the reality. Concentrated; even at low strength the palate is silky, heady, and haunting, and lasts forever in the dry glass. A legend is born. (Eight bottles only for the U.S.) Editor's Choice."
3,4,"Compass Box The General, 53.4%",Blended Malt Scotch Whisky,96,325,$,"With a name inspired by a 1926 Buster Keaton movie, only 1,698 bottles produced, and the news that one of the two batches is more than 30 years old, the clues were there that this blend was never going to be cheap. It isn't, but it's superb, rich in flavor that screams dusty old oak office, fresh polish, and Sunday church, with spices, oak dried fruits, squiggly raisins, and a surprising melting fruit-and-nut dairy chocolate back story."
4,5,"Chivas Regal Ultis, 40%",Blended Malt Scotch Whisky,96,160,$,"Captivating, enticing, and wonderfully charming, this first blended malt from Chivas Regal contains selections of five Speyside malts: Strathisla, Longmorn, Tormore, Allt-a-Bhainne, and Braeval. Red apple, cherry, raspberry fudge, peach and mango fruit salad, dusting of cinnamon, and dry heather sprigs. In essence, it’s rich and satisfying, with dark vanilla, apricot, Bourneville-covered Brazil nuts, and tangerine, smoothed over by caramel and wood spices, maltiness, and gingersnap biscuits. Quite heavenly. Editor's Choice"

Now we'll reorganize the data a little bit with panda functions to make it more practical to store in a table.

In [13]:
# Clean data
# Remove the specified columns
df.drop(['currency'], axis=1, inplace=True)

# Drop the first column
df.drop(columns=df.columns[0], inplace=True)

# Remove rows without a price
df.dropna(subset=['price'], inplace=True)

# Ensure values in 'price' are numbers
df = df[pd.to_numeric(df['price'], errors='coerce').notna()]

# Replace NaN values in other columns with an empty string
df.fillna('', inplace=True)

df.head()

,name,category,review.point,price,description
0,"Johnnie Walker Blue Label, 40%",Blended Scotch Whisky,97,225,"Magnificently powerful and intense. Caramels, dried peats, elegant cigar smoke, seeds scraped from vanilla beans, brand new pencils, peppercorn, coriander seeds, and star anise make for a deeply satisfying nosing experience. Silky caramels, bountiful fruits of ripe peach, stewed apple, orange pith, and pervasive smoke with elements of burnt tobacco. An abiding finish of smoke, dry spices, and banoffee pie sweetness. Close to perfection. Editor's Choice"
1,"Black Bowmore, 1964 vintage, 42 year old, 40.5%",Single Malt Scotch,97,4500.00,"What impresses me most is how this whisky evolves; it's incredibly complex. On the nose and palate, this is a thick, viscous, whisky with notes of sticky toffee, earthy oak, fig cake, roasted nuts, fallen fruit, pancake batter, black cherry, ripe peach, dark chocolate-covered espresso bean, polished leather, tobacco, a hint of wild game, and lingering, leafy damp kiln smoke. Flavors continue on the palate long after swallowing. This is what we all hope for (and dream of) in an older whisky!"
2,"Bowmore 46 year old (distilled 1964), 42.9%",Single Malt Scotch,97,13500.00,"There have been some legendary Bowmores from the mid-60s and this is every bit their equal. All of them share a remarkable aroma of tropical fruit, which here moves into hallucinatory intensity: guava, mango, peach, pineapple, grapefruit. There’s a very light touch of peat smoke, more a memory of Islay than the reality. Concentrated; even at low strength the palate is silky, heady, and haunting, and lasts forever in the dry glass. A legend is born. (Eight bottles only for the U.S.) Editor's Choice."
3,"Compass Box The General, 53.4%",Blended Malt Scotch Whisky,96,325,"With a name inspired by a 1926 Buster Keaton movie, only 1,698 bottles produced, and the news that one of the two batches is more than 30 years old, the clues were there that this blend was never going to be cheap. It isn't, but it's superb, rich in flavor that screams dusty old oak office, fresh polish, and Sunday church, with spices, oak dried fruits, squiggly raisins, and a surprising melting fruit-and-nut dairy chocolate back story."
4,"Chivas Regal Ultis, 40%",Blended Malt Scotch Whisky,96,160,"Captivating, enticing, and wonderfully charming, this first blended malt from Chivas Regal contains selections of five Speyside malts: Strathisla, Longmorn, Tormore, Allt-a-Bhainne, and Braeval. Red apple, cherry, raspberry fudge, peach and mango fruit salad, dusting of cinnamon, and dry heather sprigs. In essence, it’s rich and satisfying, with dark vanilla, apricot, Bourneville-covered Brazil nuts, and tangerine, smoothed over by caramel and wood spices, maltiness, and gingersnap biscuits. Quite heavenly. Editor's Choice"

## Creating the table in IRIS SQL

Now, InterSystems IRIS supports vectors as a datatype in tables! Here, we create a table with a few different columns. The last column, `description_vector` of type `VECTOR(FLOAT, 384)`, will be used to store vectors that are generated by passing the `description` of a review through an embedding model. In versions earlier than 2024.3, new VECTORs were stored with doubles. Starting in 2024.3, new VECTORs are stored with floats, and 384 is the number of dimensions the chosen embedding model uses.

In [14]:
with engine.connect() as conn:
    with conn.begin():# Load 
        sql = f"""
                CREATE TABLE IF NOT EXISTS scotch_reviews (
                    name VARCHAR(255),
                    category VARCHAR(255),
                    review_point INT,
                    price DOUBLE,
                    description VARCHAR(2000),
                    description_vector VECTOR(FLOAT, 384)
                )
                """
        result = conn.execute(text(sql))

## Creating the embeddings

Next, we'll create the embeddings for the `description` column. In IRIS 2024.3, you can leave this work to IRIS by using the new [`EMBEDDING` datatype](https://docs.intersystems.com/iris20243/csp/docbook/DocBook.UI.Page.cls?KEY=GSQL_vecsearch#GSQL_vecsearch_insembed), but for now we'll go with classic Pythonic ways of creating them, based on a common Sentence Transformer model.

In [15]:
# Load a pre-trained sentence transformer model. This model's output vectors are of size 384
model = SentenceTransformer('all-MiniLM-L6-v2')

In [16]:
# Generate embeddings for all descriptions at once.
# Batch processing before inserting into the table makes it faster, but this step may still take a minute
embeddings = model.encode(df['description'].tolist(), normalize_embeddings=True)

# Add the embeddings to the DataFrame
df['description_vector'] = embeddings.tolist()

df.head()

,name,category,review.point,price,description,description_vector
0,"Johnnie Walker Blue Label, 40%",Blended Scotch Whisky,97,225,"Magnificently powerful and intense. Caramels, dried peats, elegant cigar smoke, seeds scraped from vanilla beans, brand new pencils, peppercorn, coriander seeds, and star anise make for a deeply satisfying nosing experience. Silky caramels, bountiful fruits of ripe peach, stewed apple, orange pith, and pervasive smoke with elements of burnt tobacco. An abiding finish of smoke, dry spices, and banoffee pie sweetness. Close to perfection. Editor's Choice","[-0.010494410060346127, 0.014728964306414127, 0.07107517868280411, 0.07168121635913849, -0.09378078579902649, 0.05828458070755005, 0.04451198875904083, -0.10453858226537704, -0.011012355796992779, -0.024054810404777527, -0.003211232600733638, -0.0030189226381480694, -0.041422486305236816, -0.10920152813196182, 0.022039463743567467, -0.012925509363412857, 0.1408734768629074, 0.04734039306640625, -0.0181045513600111, -0.045829758048057556, 0.023237664252519608, 0.028599485754966736, 0.011243208311498165, 0.008574562147259712, -0.0049756113439798355, -0.014428268186748028, -0.08462360501289368, -0.028464509174227715, -0.014769266359508038, -0.0989932045340538, 0.048808690160512924, 0.01899283565580845, -0.017683424055576324, 0.047632403671741486, -0.08089730888605118, -0.060498811304569244, 0.057575054466724396, -0.06382284313440323, 0.04217085242271423, 0.03707906976342201, 0.03757086023688316, 0.0308681670576334, 0.02773617021739483, 0.02082977443933487, -0.04957350343465805, -0.03377845883369446, -0.04383726418018341, -0.08270008862018585, -0.0018084102775901556, -0.007278538774698973, -0.07975497841835022, -0.005574704613536596, -0.05512424185872078, -0.09189057350158691, 0.01140710897743702, -0.011583429761230946, -0.008846980519592762, -0.044551048427820206, 0.02972826361656189, 0.04385065287351608, 0.04125114530324936, 0.011898156255483627, 0.018097639083862305, -3.75889430870302e-05, -0.03402797505259514, -0.0930350124835968, -0.03562416136264801, 0.032002855092287064, 0.07393958419561386, -0.016465814784169197, -0.021896837279200554, 0.013922362588346004, -0.006959624122828245, 0.026779083535075188, -0.08001650124788284, 0.07227552682161331, -0.043003298342227936, -0.11346984654664993, -0.05615014210343361, -0.052093956619501114, -0.030640365555882454, 0.007509766612201929, -0.034583669155836105, 0.03335373476147652, -0.04380720853805542, -0.008800562471151352, 0.034235864877700806, 0.007948406971991062, 0.011728066951036453, 0.05204790085554123, 0.0417921245098114, 0.017680887132883072, -0.04897450655698776, -0.0031708907335996628, -0.03496548905968666, -0.04824678972363472, 0.08090456575155258, -0.059661075472831726, -0.05657698214054108, -0.004331262782216072, ...]"
1,"Black Bowmore, 1964 vintage, 42 year old, 40.5%",Single Malt Scotch,97,4500.00,"What impresses me most is how this whisky evolves; it's incredibly complex. On the nose and palate, this is a thick, viscous, whisky with notes of sticky toffee, earthy oak, fig cake, roasted nuts, fallen fruit, pancake batter, black cherry, ripe peach, dark chocolate-covered espresso bean, polished leather, tobacco, a hint of wild game, and lingering, leafy damp kiln smoke. Flavors continue on the palate long after swallowing. This is what we all hope for (and dream of) in an older whisky!","[0.023181229829788208, -0.051230352371931076, 0.030974963679909706, 0.04226924479007721, 0.020904693752527237, 0.021049195900559425, 0.0038719179574400187, -0.05376063287258148, -0.06922625005245209, 0.0248184185475111, -0.03681354224681854, 0.021754834800958633, -0.10021965950727463, 0.03083939291536808, 7.45014040148817e-05, 0.019917763769626617, -0.007203482091426849, -0.10855856537818909, 0.027342181652784348, -0.005101251415908337, 0.08838564902544022, 0.06689846515655518, 0.07319564372301102, -0.0036896485835313797, -0.01958991400897503, 0.020985599607229233, 0.07909869402647018, 0.06016898900270462, 0.007292221300303936, -0.10312464088201523, 0.012106597423553467, 0.007006049156188965, -0.021552976220846176, -0.07709448039531708, -0.10210668295621872, -0.017879057675600052, 0.05808089300990105, 0.037840645760297775, 0.07186312973499298, -0.055401746183633804, -0.04626467078924179, 0.047900691628456116, -0.005090782418847084, 0.08084890991449356, -0.04411380738019943, -0.00972597673535347, -0.06980597972869873, 0.030523376539349556, -0.013239800930023193, -0.03596113994717598, -0.019216593354940414, -0.08444686979055405, 0.032728735357522964, -0.04015813022851944, 0.04800141602754593, -0.010246135294437408, -0.04315822944045067, -0.02403002791106701, 0.014753731898963451, 0.04338657483458519, -0.049256160855293274, -0.01758703961968422, 0.016954496502876282, -0.013672593981027603, 0.04258435219526291, -0.045035410672426224, 0.008249915204942226, 0.053658973425626755, 0.0422784648835659, -0.02493838034570217, 0.02439194731414318, -0.03592570498585701, 0.04230700433254242, 0.03357240557670593, -0.09782935678958893, 0.03036850318312645, -0.04407156631350517, 0.014508566819131374, -0.029892586171627045, 0.020930754020810127, -0.04486903175711632, 0.030542584136128426, 0.000788914505392313, 0.003129338612779975, -0.05671655014157295, -0.04990816488862038, -0.028119949623942375, -0.059169597923755646, -0.08524776995182037, 0.007277999073266983, -0.010622634552419186, -0.005060612689703703, -0.05109129473567009, -0.0696190819144249, 0.0739484503865242, 0.006537304259836674, -0.015186559408903122, 0.031162885949015617, -0.019055604934692383, 0.008106679655611515, ...]"
2,"Bowmore 46 year old (distilled 1964), 42.9%",Single Malt Scotch,97,13500.00,"There have been some legendary Bowmores from the mid-60s and this is every bit their equal. All of them share a remarkable aroma of tropical fruit, which here moves into hallucinatory intensity: guava, mango, peach, pineapple, grapefruit. There’s a very light touch of peat smoke, more a memory of Islay than the reality. Concentrated; even at low strength the palate is silky, heady, and haunting, and lasts forever in the dry glass. A legend is born. (Eight bottles only for the U.S.) Editor's Choice.","[0.04333316907286644, -0.01706668920814991, -0.045239631086587906, 0.04066922515630722, 0.0010712636867538095, 0.026281608268618584, 0.003290741238743067, -0.07629942893981934, 0.01498782355338335, -0.04471844807267189, -0.002106565749272704, -0.029115211218595505, -0.06126309186220169, 0.009362839162349701, 0.07561229169368744, 0.011986097320914268, -0.018349481746554375, -0.020557427778840065, 0.02647489868104458, -0.06063936650753021, 0.02926413156092167, 0.06959507614374161, -0.023123683407902718, 0.10012511163949966, 0.018755650147795677, -0.04364638030529022, -0.0032002548687160015, 0.021726392209529877, -0.048903994262218475, -0.07257013767957687, -0.007364421617239714, 0.004774218890815973, 0.01238368172198534, -0.030490251258015633, -0.04127092659473419, -0.005878725089132786, 0.05183969438076019, -0.002224141964688897, 0.06873832643032074, 0.01782034896314144, -0.014629167504608631, 0.045126449316740036, 0.029765689745545387, -0.016503101214766502, -0.06120004877448082, 0.017944859340786934, -0.03122413344681263, -0.003472309559583664, 0.0016137780621647835, 0.014043012633919716, -0.008343223482370377, 0.002893286757171154, 0.015858661383390427, -0.08834662288427353, 0.04623894765973091, -0.05146874487400055, 0.05627511069178581, -0.07162179797887802, 0.044918242841959, 0.04044778272509575, 0.005752003751695156, -0.021915316581726074, -0.022579731419682503, -0.03257446736097336, -0.06218685209751129, -0.029566079378128052, -0.08589361608028412, 0.07852987945079803, 0.05992068350315094, -0.07573924213647842, -0.013096082955598831, -0.052046675235033035, -0.023533765226602554, 0.07951638102531433, -0.09247756004333496, -0.003017693292349577, -0.07139670848846436, -0.0744282528758049, -0.08073490113019943, 0.03646727651357651, -0.03277664631605148, -0.014016703702509403, -0.054744649678468704, 0.021275533363223076, 0.018189914524555206, 0.00793084129691124, -0.06183934584259987, 0.008826430886983871, -0.07473614811897278, -0.021380936726927757, -0.0015109297819435596, -0.02292144112288952, -0.08051993697881699, -0.013379178941249847, 0.05692537501454353, -0.013072922825813293, 0.04308769851922989, -0.06637204438447952, -0.04706316441297531, 0.008392583578824997, ...]"
3,"Compass Box The General, 53.4%",Blended Malt Scotch Whisky,96,325,"With a name inspired by a 1926 Buster Keaton movie, only 1,698 bottles produced, and the news that one of the two batches is more than 30 years old, the clues were there that this blend was never going to be cheap. It isn't, but it's superb, rich in flavor that screams dusty old oak office, fresh polish, and Sunday church, with spices, oak dried fruits, squiggly raisins, and a surprising melting fruit-and-nut dairy chocolate back story.","[-0.0759400725364685, -0.03676233068108559, 0.011379407718777657, 0.03756179288029671, -0.03959758207201958, 0.05919616296887398, -0.07268951088190079, 0.027881469577550888, -0.04667132720351219, -0.07972807437181473, 0.03034832514822483, -0.025805514305830002, -0.04384559765458107, -0.017866164445877075, -0.017342155799269676, -0.012432464398443699, 0.05217478424310684, -0.05093904584646225, -0.005354874301701784, -0.05225164815783501, -0.01731841266155243, -0.03715727850794792, 0.013760589994490147, 0.06584309786558151, 0.09062696248292923, 0.08372902870178223, 0.01634954661130905, -0.07881712168455124, 0.01604146882891655, -0.07130265980958939, 0.05629763379693031, 0.061106353998184204, -0.02077469415962696, -0.0260833278298378, 0.05242154374718666, -0.05762694776058197, 0.04959235340356827, 0.03616130352020264, 0.06913892179727554, 0.042531535029411316, 0.0017110002227127552, 0.044165439903736115, -0.023854142054915428, 0.025804337114095688, -0.039113178849220276, -0.04384088143706322, 0.006712773349136114, 0.03454435244202614, 0.051271602511405945, -0.014291309751570225, -0.05732807144522667, -0.0676550343632698, 0.006566827185451984, -0.12884342670440674, 0.036847393959760666, -0.04726371914148331, -0.028520388528704643, -0.03433891385793686, 0.01776968687772751, 0.12553143501281738, 0.02177262306213379, -0.050440624356269836, 0.025896724313497543, -0.025758691132068634, 0.02312270551919937, -0.04349055886268616, -0.033405791968107224, -0.0410875640809536, -0.018170788884162903, -0.044314753264188766, -0.03227892890572548, -0.01031122263520956, 0.010906632989645004, 0.0434865765273571, -0.04271262511610985, -0.006373604293912649, 0.026092737913131714, -0.11638306081295013, -0.06211201846599579, 0.0234543364495039, 0.003660848829895258, -0.07458053529262543, -0.039459243416786194, 0.017170310020446777, -0.033407118171453476, -0.024778330698609352, 0.01048992294818163, -0.02749047242105007, 0.026846392080187798, -0.026523638516664505, -0.02788482792675495, 0.01573783904314041, -0.06931504607200623, -0.029240289703011513, 0.004105341155081987, 0.018677569925785065, -0.04563796892762184, 0.09989292174577713, 0.046256937086582184, 0.05756652355194092, ...]"
4,"Chivas Regal Ultis, 40%",Blended Malt Scotch Whisky,96,160,"Captivating, enticing, and wonderfully charming, this first blended malt from Chivas Regal contains selections of five Speyside malts: Strathisla, Longmorn, Tormore, Allt-a-Bhainne, and Braeval. Red apple, cherry, raspberry fudge, peach and mango fruit salad, dusting of cinnamon, and dry heather sprigs. In essence, it’s rich and satisfying, with dark vanilla, apricot, Bourneville-covered Brazil nuts, and tangerine, smoothed over by caramel and wood spices, maltiness, and gingersnap biscuits. Quite heavenly. Editor's Choice","[-0.012818887829780579, -0.097697913646698, 0.02304936945438385, 0.045914191752672195, -0.01598571240901947, 0.03197157382965088, 0.03260761871933937, 0.032540906220674515, -0.02113412693142891, -0.06523427367210388, 0.09448981285095215, 0.005696471314877272, -0.060422759503126144, -0.09505900740623474, -0.0006422798032872379, -0.0396590493619442, 0.05477263405919075, -0.02438969910144806, 0.04716477170586586, -0.021247388795018196, 0.04038208723068237, -0.0007846102816984057, -0.02100030705332756, 0.05812327191233635, -0.03273213282227516, 0.0490485243499279, 0.022592009976506233, -0.0037811261136084795, -0.06667399406433105, -0.0915798544883728, 0.004669340327382088, 0.009521549567580223, -0.011276875622570515, 0.007857611402869225, -0.10926979035139084, 0.01358888577669859, 0.035268634557724, -0.0334637351334095, 0.11992499977350235, 0.016197344288229942, 0.013939212076365948, 0.012065721675753593, -0.020216936245560646, 0.06204259768128395, -0.07523205131292343, -0.08411760628223419, -0.0693650171160698, -0.024813415482640266, -0.025018278509378433, -0.008869397453963757, -0.06881868839263916, 0.0062460387125611305, -0.023946117609739304, -0.019758770242333412, -0.01487057190388441, -0.000623906496912241, -0.0898992270231247, -0.026118086650967598, 0.03764171525835991, 0.025473667308688164, -0.008949773386120796, 0.09807047247886658, -0.07445573806762695, -0.020642494782805443, -0.07209552824497223, -0.06422218680381775, -0.05474335327744484, -0.0038270854856818914, -0.016074365004897118, -0.022127002477645874, -0.030018268153071404, -0.06707808375358582, -0.029017720371484756, 0.07382533699274063, 0.0091150663793087, 0.04858373478055, 0.02768041379749775, -0.09974027425050735, -0.12693651020526886, -0.00885623786598444, -0.041182540357112885, 0.0491524375975132, 0.00014371337601915002, 0.04277497157454491, -0.03785187751054764, -0.08486335724592209, 0.02174707129597664, -0.004807362798601389, 0.06219733506441116, 0.06531104445457458, 0.06081175431609154, -0.014233557507395744, -0.005182502791285515, -0.006419418379664421, -0.014985145069658756, 0.042094942182302475, -0.028310725465416908, -0.1057315394282341, -0.009128586389124393, 0.040890805423259735, ...]"

Now we'll load the data into our table. Note the `str()` call as we're passing the vector as a comma-separated list of values in string format, because there is no specific vector datatype in the DB-API driver standard.

In [17]:
with engine.connect() as conn:
    with conn.begin():
        for index, row in df.iterrows():
            sql = text("""
                INSERT INTO scotch_reviews 
                (name, category, review_point, price, description, description_vector) 
                VALUES (:name, :category, :review_point, :price, :description, TO_VECTOR(:description_vector))
            """)
            conn.execute(sql, {
                'name': row['name'], 
                'category': row['category'], 
                'review_point': row['review.point'], 
                'price': row['price'], 
                'description': row['description'], 
                'description_vector': str(row['description_vector'])
            })

## Running a few queries

Let's look for a scotch that costs less than $100, and has an earthy and creamy taste.

In [18]:
description_search = "earthy and creamy taste"
search_vector = model.encode(description_search, normalize_embeddings=True).tolist() # Convert search phrase into a vector

In [19]:
with engine.connect() as conn:
    with conn.begin():
        sql = text("""
            SELECT TOP 3 * FROM scotch_reviews 
            WHERE price < 100 
            ORDER BY VECTOR_DOT_PRODUCT(description_vector, TO_VECTOR(:search_vector)) DESC
        """)

        results = conn.execute(sql, {'search_vector': str(search_vector)}).fetchall()

print(results)

[('Signatory (distilled at Bowmore), 16 year old, 1988 vintage, cask #42508, 46%', 'Single Malt Scotch', 87, 60.0, 'Medium-bodied and nicely textured. Good balance of flavors -- and well-integrated, too -- with lovely sweet notes (cereal grain, cookie dough, carame ... (48 characters truncated) ...  fishnets, and brine that is complementary, but not aggressive, with a suggestion of lavender and tangerine. Balanced finish. (332 bottles produced.)', '-.048620373010635375976,-.082065798342227935791,.039660677313804626464,-.018970934674143791198,-.017485296353697776794,.042453121393918991088,.046325 ... (8851 characters truncated) ... 483276,-.0038619611877948045731,-.022344652563333511352,.052769269794225692749,-.061306405812501907348,.048756964504718780517,-.063436627388000488281'), ('Signatory (distilled at Bowmore), 16 year old, 1988 vintage, cask #42508, 46%', 'Single Malt Scotch', 87, 60.0, 'Medium-bodied and nicely textured. Good balance of flavors -- and well-integrated, too -- with lovely sweet notes (cereal grain, cookie dough, carame ... (48 characters truncated) ...  fishnets, and brine that is complementary, but not aggressive, with a suggestion of lavender and tangerine. Balanced finish. (332 bottles produced.)', '-.048620373010635375976,-.082065798342227935791,.039660677313804626464,-.018970934674143791198,-.017485296353697776794,.042453121393918991088,.046325 ... (8851 characters truncated) ... 483276,-.0038619611877948045731,-.022344652563333511352,.052769269794225692749,-.061306405812501907348,.048756964504718780517,-.063436627388000488281'), ('Shieldaig 12 year old, 40%', 'Blended Scotch Whisky', 85, 31.0, 'This is a sharp dresser, with a firm, solid mouthfeel and an altogether finer and more focused taste than Shieldaig Classic (see\r\nbelow). It’s not  ... (114 characters truncated) ... e, and some soft fruit, including a touch of overripe banana and melon notes. The savoriness this time comes from a touch of pepper rather than salt.', '-.0049302731640636920928,-.070051766932010650634,.046160347759723663331,.053877636790275573731,.0037386573385447263717,.018159849569201469421,.076887 ... (8824 characters truncated) ... 4065551,-.0015221304493024945259,.047901269048452377319,.0098907314240932464599,-.026278624311089515686,.042504720389842987061,.041063353419303894042')]

Let's print that result a little more nicely!

In [20]:
results_df = pd.DataFrame(results, columns=df.columns).iloc[:, :-1] # Remove vector
pd.set_option('display.max_colwidth', None)  # Easier to read description
results_df.head()

,name,category,review.point,price,description
0,"Signatory (distilled at Bowmore), 16 year old, 1988 vintage, cask #42508, 46%",Single Malt Scotch,87,60.0,"Medium-bodied and nicely textured. Good balance of flavors -- and well-integrated, too -- with lovely sweet notes (cereal grain, cookie dough, caramel, and vanilla cream), young heathery peat, tar, fishnets, and brine that is complementary, but not aggressive, with a suggestion of lavender and tangerine. Balanced finish. (332 bottles produced.)"
1,"Signatory (distilled at Bowmore), 16 year old, 1988 vintage, cask #42508, 46%",Single Malt Scotch,87,60.0,"Medium-bodied and nicely textured. Good balance of flavors -- and well-integrated, too -- with lovely sweet notes (cereal grain, cookie dough, caramel, and vanilla cream), young heathery peat, tar, fishnets, and brine that is complementary, but not aggressive, with a suggestion of lavender and tangerine. Balanced finish. (332 bottles produced.)"
2,"Shieldaig 12 year old, 40%",Blended Scotch Whisky,85,31.0,"This is a sharp dresser, with a firm, solid mouthfeel and an altogether finer and more focused taste than Shieldaig Classic (see\r\nbelow). It’s not coastal or earthy particularly, either. Instead the flavors are softer and built around mocha, smooth creamy toffee, and some soft fruit, including a touch of overripe banana and melon notes. The savoriness this time comes from a touch of pepper rather than salt."

## Indexing vector data

**IRIS 2025.3** continues to improve performance for vector search through enhancements to the internal layout of the disk-based Approximate Nearest Neighbour (ANN) index used for large vector collections (typically over 100K vectors).

These improvements optimize duplicate entry management and reduce query-time overhead. Benchmarks show **up to ~10% improvements in throughput and latency**, depending on workload characteristics.

See [the docs](https://docs.intersystems.com/iris20253/csp/docbook/DocBook.UI.Page.cls?KEY=GSQL_vecsearch#GSQL_vecsearch_index) for more information on how to define and use the index.

```SQL
CREATE INDEX HNSWIndex ON TABLE scotch_reviews (description_vector) AS HNSW(M=80, Distance='DotProduct');
```

The index will automatically get used if you issue a query that uses a `TOP` clause and an `ORDER BY` to sort by the distance function for which the index was created. You can verify its use in the query plan, by using the `EXPLAIN` command or checking the plan through the System Management Portal UI.

```SQL
SELECT TOP 10 * FROM scotch_reviews ORDER BY VECTOR_DOT_PRODUCT(description_vector, TO_VECTOR(:search_vector)) DESC;
```

Since this notebook is working with a dataset much smaller than 100K rows, there won't be a measurable performance benefit, and this is provided as an example you can adapt.